genetic_operators:
  crossover:
    # all options: one_point, two_points, anular, uniform
    opt: one_point
    params:
      # in case of one_point
      p: 4 

      # in case of two_points
      p1: 2
      p2: 4
      
      # in case of anular (Cruce anular)
      ap: 3
      l: 3

      # in case of uniform (Cruce uniforme)
      # up between [0.0 - 1.0]
      up: 0.5

  mutation:
    # all options: gen, multi_limited, multi_uniform, full 
    opt: multi_uniform
    params:
      # in case of gen (p is the probability to mutate only one gene)\
      # p between [0.0 - 1.0]
      pg: 0.5

      # in case of multi_limited (p is the probability to mutate [1-M] gens at random [where M is the ammount of gens])
      # p between [0.0 - 1.0]
      pml: 0.5
      
      # in case of multi_uniform (p is the probability of each gene to mutate)
      # p between [0.0 - 1.0]
      pmu: 0.5

      # in case of full (p is the probability of mutating all gens or none)
      # p between [0.0 - 1.0]
      pf: 0.5


selection:
  # number of individuals selected each generation
  K: 15
  # [0.0-1.0]
  A: 0.5
  B: 0.0
  # all options: elite, roulette, universal, boltzmann, det_tournaments, prob_tournaments, ranking
  method1: 
    opt: elite
    params:
      # in case of boltzmann
      initial_temp: 50 
      min_temp: 10
      k: 2
  method2: 
    opt: roulette
  method3: 
    opt: roulette
  method4: 
    opt: roulette

implementation: 
  # all options: fill_all, fill_parent
  opt: fill_all
  params:
    
    # in case of fill_all
    fill_all_n: 50

    # in case of fill_parent
    fill_parent_n: 50



stop:
  # all options: time, gens, acceptable, struct, content
  opt: time
  params:
    # in case of time, declared in seconds
    max_time: 30

    # in case of gens
    max_generation: 30

    # in case of acceptable
    mean_acceptable_fitness: 100

    # in case of struct
    # relevant_percentage_of_change: 0.7

    
    # in case of content
    max_generations_counter: 5


# path to tsv dile conataining all items info
items_dataset: 
  path: allitems
  weapons_filename: armas.tsv
  boots_filename: botas.tsv
  helmets_filename: cascos.tsv
  gloves_filename: guantes.tsv
  breastplates_filename: pecheras.tsv

# all options: warrior, archer, defender, infiltrate
character_class: warrior

# natural number greater than zero
initial_population: 20
