genetic_operators:
  crossover:
    # all options: one_point, two_points, anular, uniform
    opt: one_point
    params:
      # in case of one_point
      p: 4 

      # in case of two_points
      p1: 2
      p2: 4
      
      # in case of anular (Cruce anular)
      ap: 3
      l: 3

      # in case of uniform (Cruce uniforme)
      # up between [0.0 - 1.0]
      up: 0.5

  mutation:
    # all options: gen, multi_limited, multi_uniform, full 
    opt: multi_uniform

selection:
  # number of individuals selected each generation
  K: 140
  # [0.0-1.0]
  A: 0.5
  B: 0.0
  # all options: elite, roulette, universal, boltzmann, det_tournaments, prob_tournaments, ranking
  method1: elite
  method2: roulette
  method3: roulette
  method4: roulette

implementation: 
  # all options: fill_all, fill_parent
  opt: fill_parent

stop:
  # all options: time, gens, acceptable, struct, content
  opt: time
  params:
    # in case of time, declared in seconds
    max_time: 30

    # in case of gens
    max_generation: 30

    # in case of acceptable
    mean_acceptable_fitness: 100

    # in case of content
    max_generations_counter: 5


# path to tsv dile conataining all items info
items_dataset: 
  path: allitems
  weapons_filename: armas.tsv
  boots_filename: botas.tsv
  helmets_filename: cascos.tsv
  gloves_filename: guantes.tsv
  breastplates_filename: pecheras.tsv

# all options: warrior, archer, defender, infiltrate
character_class: warrior

# natural number greater than zero
initial_population: 160
